Feature/#76 user grade
YAPP-19th/Android-Team-2-Backend pull request #82
Opened 2021-12-03 16:10 UTC by dev-donghwan

- grade type 추가
- point 로직 추가
- grade 로직 추가
- Response 논의 필요

2021-12-03 16:15 UTC, kihwankim commented on module-api/src/main/java/com/yapp/sharefood/food/controller/FoodController.java
> +    private boolean isMainIngredientType(boolean isMain, FoodTagDto foodTags) {
오타 수정 감사합니다!

2021-12-03 16:18 UTC, kihwankim requested changes
enum을 사용할 때 ordinal 이나 배열을 사용하신 부분이있습니다.
만약 순서가 바뀌게되면 큰 사이드 이펙트가 유발될 수 있습니다.
그 부분은 무조건 수정이 필요할 거같습니다

2021-12-03 16:18 UTC, kihwankim commented on module-domain/src/main/java/com/yapp/sharefood/food/domain/FoodStatus.java
> +    }
```suggestion
    public boolean isShared() {
        return this == FoodStatus.SHARED;
    }
```
enum은 자체가 singleton 입니다 그래서 이렇게 바꾸는게 어떨까요?

2021-12-03 16:18 UTC, kihwankim commented on module-domain/src/main/java/com/yapp/sharefood/user/domain/Grade.java
> +        return values()[0];
순서가 바뀌게 되면 굉장히 위험한 코드 입니다 이부분은 무조건 enum 자체가 반환 되게 바꿔주세요

2021-12-04 02:23 UTC, kihwankim commented on module-domain/src/main/java/com/yapp/sharefood/user/domain/Grade.java
> +        return STUDENT;
foreach문으로 해서 index out of bound 이슈 해결한건 좋은시도 인거 같습니다
디자인 패턴 좋은 방식이 나오면 같이 상의해서 리팩토링 하는것도 좋을거 같네요

2021-12-04 02:24 UTC, kihwankim approved these changes
test code 작성하신다고 고생 하셨습니다.

2021-12-04 02:24 UTC, kihwankim commented on module-domain/src/test/java/com/yapp/sharefood/user/domain/GradeTest.java
> +        int point1 = 1700;
Normal오타 난거같아요 근데 크게 무리 없으면 뭐... 괜찮을듯합니다

2021-12-04 02:25 UTC, dev-donghwan commented on module-domain/src/test/java/com/yapp/sharefood/user/domain/GradeTest.java
> +        int point1 = 1700;
@kihwankim 앗 빠르게 수정하겠습니다ㅎ

2021-12-04 02:28 UTC, merged