Feature/#86 food controller test
YAPP-19th/Android-Team-2-Backend pull request #92
Opened 2021-12-08 13:11 UTC by kihwankim

- food controller 추가
- like controller 테스트 전체 케이스 추가

2021-12-08 13:12 UTC, kihwankim commented
food image 관련 controller 는 추가 하였습니다.
rank와 추천은 빠르게 해서 이번주 내로 올리도록 하겠습니다.

2021-12-08 13:50 UTC, dev-donghwan requested changes
에러 체크 한번 부탁드립니다!

2021-12-09 00:29 UTC, kihwankim commented
> 에러 체크 한번 부탁드립니다!

@dev-donghwan  에러 체크라는게 어떤걸 말씀하시는지 한번만 더 디테일하게 작성 부탁드려도 될까요?

2021-12-09 00:41 UTC, dev-donghwan commented
@kihwankim 
6f177c5
를 예로들면 마지막 에러케이스에서 OOOException.class를 던지게 되어있고 마지막에 result를 .isNotNull만 하고 있는데
이 상황에서도 저희가 부여한 ErrorMessage가 문서에 나타나는지 확인이 필요한거 같습니다. 공백으로 뜬다면 equalTO 체크가 필요해보입니다!

2021-12-09 11:32 UTC, kihwankim commented
말씀 하신거 수정완료했습니다.
그리고 추가 성능 개선 일부도 진행했습니다.

2021-12-09 11:35 UTC, dev-donghwan approved these changes
고생하셨습니다.

2021-12-09 11:36 UTC, kihwankim commented
코드 deploy에 zip 파일 파일 명 충돌이기 때문에 git action 충돌 이슈는 무시 하겠습니다.

2021-12-09 11:36 UTC, merged